### ISSUE TITLE
python and rust language support?

### ISSUE THREAD

**Issue by WindSoilder** [robertrossmann/vscode-remedy#10]

**Comment by robertrossmann** [comment]
Both languages look reasonably well with Remedy, are you seeing some colouring inconsistencies?

Rust, however, does not provide enough information about brackets and so they have a generic regular text colour instead of the intended, more dimmed one. Sadly, I cannot do anything with this - the Rust grammar would have to be extended to recognise these code symbols and assign a different token type to them.

**Comment by WindSoilder** [comment]
Thanks for your reply! For now I don't seeing some colouring inconsistencies.

I just submit this issue because I can't see python and rust in the language support session in README.. Thanks again for your theme, I will try it more

**Comment by robertrossmann** [comment]
No problem, you are welcome!

Rust is not on the list because I cannot tweak those stoopid brackets and therefore cannot claim Rust as being "supported" while knowing it does not match the intended look & feel. 😇 🎨 

As for Python, I have no idea... I probably completely forgot about it. 😱 I'll find a good, complex python sample to test the theme on, fix any discrepancies and list it as "supported". But it should look reasonably well even now.

Enjoy! 🍻
