### ISSUE TITLE
Integration for .pug/jade?

### ISSUE THREAD

**Issue by dcorso21** [robertrossmann/vscode-remedy#17]
Hi there, 

First, let me just say I love this theme. Thank you for all the work you've put into it! 

I've been using It for some front end stuff and noticed that the theme doesn't quite gel with PUG/JADE and thought it might be something you would like to be aware of.   When using PUG with remedy, the class names and id names are the same color as the body text, making it very hard to differentiate between tags, classes and content. 

It would be great if this feature was included in Remedy! I hope you will consider implementing it. 

Thank you again for making this theme!

David

**Comment by dcorso21** [comment]
![Screen Shot 2020-10-19 at 12 41 17 PM](https://user-images.githubusercontent.com/53447317/96480565-68124c00-1208-11eb-82fa-b1dfcc166c1f.png)

Here is a photo I should have included of the effect — using remedy dark tilted

**Comment by robertrossmann** [comment]
Hi @dcorso21, thanks for the suggestion! Indeed, that looks most...flat and boring!

I did some basic research and while it might be fixable to some extent, the built-in Pug parser is rather basic and does not provide a lot of flexibility in terms of selecting specific elements of the language and theming them. 🤷‍♂️ So yeah, the classes and IDs should be themeable but unless I did something wrong, applying the colouring also affected the element's properties (the things that are in the brackets after the element, ie. `img(things)`), so mostly everything was red instead of white. 🤦‍♂️ 

I'll see what I can do... Unless you are up for a challenge and would like to send a PR? 😇

**Comment by dcorso21** [comment]
I would be happy to take a look -  however, I'm a new developer and the complexity of the codebase is a little out of my depth. -- fair warning!!

**Comment by robertrossmann** [comment]
No worries, I'll take care of this myself, it just might take a while as I'm a bit busy on an actual, paid, work. 😂 I do try to make regular updates and improvements, though.

**Comment by dcorso21** [comment]
Of course! No pressure at all! I appreciate you taking the time to consider it. Like I said, I'm a big fan of the theme. Thanks for sharing it with vscode users!
