### ISSUE TITLE
Modified tab border is not prominent enough

### ISSUE THREAD

**Issue by usernamehw** [robertrossmann/vscode-remedy#3]
```js
"workbench.editor.highlightModifiedTabs": true,
```

`"tab.activeModifiedBorder"` has the same color as `"tab.activeBorderTop"` which makes them difficult to tell apart at a glance.

**Comment by robertrossmann** [comment]
Thanks for the suggestion!

I just tried various tab colouring combinations where I would use a different colour for the modified tab, or use the active tab border at the bottom instead of at the top and I simply could not find a satisfying combination. Personally I rely on the modified indicator on tabs (although I think that can be disabled... 🤔) to find which tabs have unsaved changes at a quick glance:

![Unsaved changes indicator](https://user-images.githubusercontent.com/3058150/68020061-a633fa00-fc9d-11e9-9dfc-f506ef641bf3.png)

If you prefer to use a different colour for changed tabs you can use a custom colour setting in your VS Code settings:

```json
{
  "workbench.colorCustomizations": {
    "[Remedy - Tilted]": {
      "tab.activeModifiedBorder": "#81A2BE",
      "tab.inactiveModifiedBorder": "#81A2BE66",
    },
  }
}
```

These are the `gitDecoration.modifiedResourceForeground` colours so you'd get the same colour on a modified tab as you see everywhere else where git decorations are available. 🎨
