### ISSUE TITLE
Higher contrast variant?

### ISSUE THREAD

**Issue by sahmed007** [robertrossmann/vscode-remedy#38]
Excellent theme. My only issue with it is that the parenthesis, brackets, etc are extremely low contrast. I understand it is probably with the intention to reduce visual noise, but would be good to have a slightly higher contrast variant.

**Comment by robertrossmann** [comment]
Hi @sahmed007 , thank you for your feedback! ❤️ And apologies for the late response here. The colouring of the brackets is very much intentional and is a core aspect of the theme. I'm not saying it's never going to change but right now I do not see that as something I would consider.

I hope that does not dissuade you from using and enjoying the theme! 🎨
