### ISSUE TITLE
iTerm 2 Theme

### ISSUE THREAD

**Issue by vaporwhere** [robertrossmann/vscode-remedy#5]
This is the best dark theme I've ever tried - congrats!

I've converted your Terminal theme to iTerm 2 for anyone who might be interested; would you be open to a PR?

**Comment by robertrossmann** [comment]
Hi @vaporwhere! Thanks for the suggestion! As I do not use iTerm at all, I think I would include an iTerm theme/profile (?) as an included optional asset under these circumstances:

- you would help me in situations where a correction needs to be done to the theme either due to changes in iTerm's side or in this theme (not very likely as I like the colour palette)

That's all. 😄 Basically what I am asking is if you would be willing to occasionally commit some of your time to fix issues in the iTerm theme should any be found/reported. No need to watch the repo if you do not feel like doing so, I would always notify you when things need your attention.

If, for any reason, you cannot commit to this kind of cooperation, no worries! I will be happy to include a link to this projec'ts _readme_ where people can find your iTerm profile.

Let me know! 👀

**Comment by vaporwhere** [comment]
Hi @robertrossmann , hope you had a great start to 2020! That sounds great; I'm committing to fixing any issues that come up. I'm going to open the PR and we can continue there!

**Comment by robertrossmann** [comment]
Implemented in #6 and released in [3.8.0](https://github.com/robertrossmann/vscode-remedy/releases/tag/3.8.0)! 🚀
